hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - mnist_target=2,3,4,5,6,7,8,9
  job:
    name: main
    chdir: null
    override_dirname: mnist_target=2,3,4,5,6,7,8,9
    id: ???
    num: ???
    config_name: config.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.1
    version_base: '1.3'
    cwd: /home/penquitt/Git Test/lu-network_robin/lu-network
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/penquitt/Git Test/lu-network_robin/lu-network
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
no_cuda: false
save_model: true
checkpoints_dir: ./checkpoints/
outputs_dir: ./outputs/
num_cores: 4
batch_size: 256
test_batch_size: 1200
num_epochs: 80
learning_rate: 0.6
momentum: 0.9
step_size: 3
gamma: 0.5
random_seed: 42
mnist_target: 2
data: FashionMNIST
loss_alpha: 100
num_runs: 30
num_samples: 100
another_mnist_target: null
model: LUNet
LUNet:
  _target_: model.LUNet
  num_lu_blocks: 3
  layer_size: 784
